### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by asakura42** [bgjd/MassAdd#1]
Anki 2.1.35 (84dcaa86) Python 3.9.5 Qt 5.15.2 PyQt 5.15.4
Platform: Linux
Flags: frz=False ao=True sv=1
Add-ons, last update check: 2021-06-27 02:58:40
Add-ons possibly involved: ⁨MassAdd - Create multiple cards from raw text⁩

Caught exception:
Traceback (most recent call last):
  File "/home/asakura/.local/share/Anki2/addons21/1909156369/__init__.py", line 75, in add_current_sentences
    model_id = self.model_chooser.deck.decks.current()["mid"]
KeyError: 'mid'

**Comment by bgjd** [comment]
Should be fixed now, you will probably need a newer version of anki though.
